import { ComplianceRule } from '@/types/compliance';

export const complianceRules: ComplianceRule[] = [
  {
    id: 'RULE-PC-01',
    name: 'Manufacturer / Packer / Importer Name and Address',
    clause: 'Rule 6(1)(a) - Identity & Address Declaration',
    legal_reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Rule 6(1)(a)',
    requirement: 'Name and complete address of manufacturer, packer, or importer declared on the package.',
    mandatory: true,
    applicability: 'all',
    standardPenalty: 'Section 36(1) Notice / Fine up to ₹25,000',
    description: 'Every package shall bear the name and complete address of the manufacturer, or where the manufacturer is not the packer, the name and address of the manufacturer and packer, or for imported goods, the name and address of the importer.',
    source: 'G.S.R. 202(E)',
    version: '2011.amended',
    effective_from: '2011-04-01',
  },
  {
    id: 'RULE-PC-02',
    name: 'Common / Generic Name of Commodity',
    clause: 'Rule 6(1)(b) - Common or Generic Designation',
    legal_reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Rule 6(1)(b)',
    requirement: 'The common or generic name of the commodity contained in the package must be clearly declared.',
    mandatory: true,
    applicability: 'all',
    standardPenalty: 'Section 36(1) Notice / Compoundable Proceedings',
    description: 'The common or generic names of the commodity contained in the package and, in case of packages with more than one product, the name and quantity of each product shall be declared.',
    source: 'G.S.R. 202(E)',
    version: '2011.amended',
    effective_from: '2011-04-01',
  },
  {
    id: 'RULE-PC-03',
    name: 'Net Quantity Declaration',
    clause: 'Rule 6(1)(c), Rule 11 & Rule 12 - Standard Net Quantity',
    legal_reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Rule 6(1)(c), 11 & 12',
    requirement: 'Net quantity declared on the principal display panel in standard metric units or number.',
    mandatory: true,
    applicability: 'all',
    standardPenalty: 'Section 36(1) Direct Seizure / Fine up to ₹50,000 for repeat offences',
    description: 'The net quantity shall be declared on the principal display panel in standard metric units (g, kg, ml, l, m, cm, unit/number) with permissible maximum error limits as specified under the Second Schedule.',
    source: 'G.S.R. 202(E) & Second Schedule',
    version: '2011.amended',
    effective_from: '2011-04-01',
  },
  {
    id: 'RULE-PC-04',
    name: 'Month and Year of Manufacture / Pre-packing / Import',
    clause: 'Rule 6(1)(d) - Date of Manufacture or Pre-packing',
    legal_reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Rule 6(1)(d)',
    requirement: 'Month and year of manufacture, pre-packing, or import declared in words or numerals.',
    mandatory: true,
    applicability: 'all',
    standardPenalty: 'Section 36(1) Statutory Notice',
    description: 'The month and year in which the commodity is manufactured or pre-packed or imported shall be mentioned clearly in standard MM/YYYY or Month YYYY format.',
    source: 'G.S.R. 202(E)',
    version: '2011.amended',
    effective_from: '2011-04-01',
  },
  {
    id: 'RULE-PC-05',
    name: 'Maximum Retail Price (MRP)',
    clause: 'Rule 6(1)(e) - Retail Sale Price Declaration',
    legal_reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Rule 6(1)(e)',
    requirement: 'The retail sale price of the package declared in Indian currency as MRP.',
    mandatory: true,
    applicability: 'all',
    standardPenalty: 'Section 36(1) Penalty up to ₹25,000 for first offence',
    description: 'The retail sale price of the package shall be declared in Indian Rupees as Maximum Retail Price or MRP, with the currency symbol ₹ or Rs.',
    source: 'G.S.R. 202(E)',
    version: '2011.amended',
    effective_from: '2011-04-01',
  },
  {
    id: 'RULE-PC-06',
    name: 'MRP Inclusive of All Taxes',
    clause: 'Rule 6(1)(e) Proviso - Tax-Inclusive Affirmation',
    legal_reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Rule 6(1)(e) Proviso',
    requirement: 'MRP must be stated explicitly as inclusive of all taxes.',
    mandatory: true,
    applicability: 'all',
    standardPenalty: 'Section 36(1) Statutory Notice',
    description: 'The MRP declaration shall be expressed in the form: Maximum or Max. Retail Price Rs./₹ ... (incl. of all taxes) or (inclusive of all taxes).',
    source: 'G.S.R. 779(E) Amendment',
    version: '2017.amended',
    effective_from: '2018-01-01',
  },
  {
    id: 'RULE-PC-07',
    name: 'Unit Sale Price (USP)',
    clause: 'Rule 6(1)(da) - Unit Sale Price per g/ml or kg/l',
    legal_reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Rule 6(1)(da)',
    requirement: 'Unit sale price in rupees rounded off to nearest two decimal places where applicable.',
    mandatory: false,
    applicability: 'conditional',
    standardPenalty: 'Section 36(1) Compliance Warning',
    description: 'Declaration of unit sale price in rupees rounded off to the nearest two decimal places for packages containing commodities more than 1 kg or 1 L or sold by number.',
    source: 'G.S.R. 779(E)',
    version: '2021.amended',
    effective_from: '2022-12-01',
  },
  {
    id: 'RULE-PC-08',
    name: 'Consumer Care Contact Details',
    clause: 'Rule 6(1)(h) - Consumer Redressal Contact Info',
    legal_reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Rule 6(1)(h)',
    requirement: 'Name, address, phone number, and email address for consumer grievances.',
    mandatory: true,
    applicability: 'all',
    standardPenalty: 'Section 36(1) Notice / Fine',
    description: 'Name, address, telephone number and email address of the person who can be contacted by the consumer in case of complaints or consumer care details.',
    source: 'G.S.R. 202(E)',
    version: '2011.amended',
    effective_from: '2011-04-01',
  },
  {
    id: 'RULE-PC-09',
    name: 'Country of Origin for Imported Packages',
    clause: 'Rule 6(10) & Rule 6(1)(d) Proviso - Origin Declaration',
    legal_reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Rule 6(10)',
    requirement: 'Country of origin or manufacture stated clearly for all imported packages.',
    mandatory: false,
    applicability: 'imported',
    standardPenalty: 'Section 36(1) Seizure of Imported Goods',
    description: 'For imported packages, the name of the country of origin or manufacture shall be mentioned clearly on the label.',
    source: 'G.S.R. 584(E)',
    version: '2017.amended',
    effective_from: '2018-01-01',
  },
  {
    id: 'RULE-PC-10',
    name: 'Best Before / Use By Declaration',
    clause: 'Rule 6(1) Proviso - Perishable Product Shelf Life',
    legal_reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Rule 6(1) Proviso',
    requirement: 'Best before or use by date declaration for perishable commodities.',
    mandatory: false,
    applicability: 'conditional',
    standardPenalty: 'Section 36(1) Notice',
    description: 'Packages of commodities that may become unfit for consumption after a period shall bear best before or use by date declarations.',
    source: 'Legal Metrology Rules, 2011',
    version: '2011.amended',
    effective_from: '2011-04-01',
  },
  {
    id: 'RULE-PC-11',
    name: 'Standard Units and Symbols',
    clause: 'Rule 13 & Schedules - Metric System Symbols',
    legal_reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Rule 13',
    requirement: 'Standard metric symbols (g, kg, ml, L, m, cm, unit/N) without pluralization.',
    mandatory: true,
    applicability: 'all',
    standardPenalty: 'Section 36(1) Compliance Warning / Notice',
    description: 'The unit of measurement shall be in accordance with the International System of Units (SI) - e.g., "g" or "kg" for mass, "ml" or "L" for volume, "m" or "cm" for length, without non-standard abbreviations.',
    source: 'Rule 13 & First/Second Schedules',
    version: '2011.amended',
    effective_from: '2011-04-01',
  },
  {
    id: 'RULE-PC-12',
    name: 'Size of Letters and Numerals',
    clause: 'Rule 7 & Table 1 - Minimum Letter Height',
    legal_reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Rule 7',
    requirement: 'Numeral and letter heights meet minimum height standards based on PDP area.',
    mandatory: true,
    applicability: 'all',
    standardPenalty: 'Section 36(1) Notice',
    description: 'The height of any numeral and letter in the declaration on the principal display panel shall not be less than the minimum height prescribed in Table 1 where technically measurable.',
    source: 'Rule 7 & Table 1',
    version: '2011.amended',
    effective_from: '2011-04-01',
  },
  {
    id: 'RULE-PC-13',
    name: 'Manner / Visibility / Legibility of Declarations',
    clause: 'Rule 9 - Conspicuous and Prominent Display',
    legal_reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Rule 9',
    requirement: 'All declarations are plain, prominent, legible and distinct from background.',
    mandatory: true,
    applicability: 'all',
    standardPenalty: 'Section 36(1) Notice',
    description: 'All declarations required to be made on a package shall be legible and conspicuous, with distinct contrast between the background and the inscription.',
    source: 'Rule 9',
    version: '2011.amended',
    effective_from: '2011-04-01',
  },
  {
    id: 'RULE-PC-14',
    name: 'Principal Display Panel (PDP) Grouping and Placement',
    clause: 'Rule 2(h) & Rule 6 - Grouping on Principal Display Panel',
    legal_reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Rule 2(h)',
    requirement: 'Mandatory declarations grouped together on the principal display panel.',
    mandatory: true,
    applicability: 'all',
    standardPenalty: 'Section 36(1) Notice',
    description: 'All mandatory declarations (generic name, net quantity, retail sale price, manufacturing date) shall be grouped together and displayed clearly on the principal display panel.',
    source: 'Rule 2(h) & Rule 6',
    version: '2011.amended',
    effective_from: '2011-04-01',
  },
  {
    id: 'RULE-PC-15',
    name: 'Commodity-Specific / Conditional Requirements',
    clause: 'Rule 26 & Schedules - Special Sizes & Package Exemptions',
    legal_reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Rule 26',
    requirement: 'Support for commodity-specific standard pack sizes and small package exemptions (<= 10g/10ml).',
    mandatory: false,
    applicability: 'conditional',
    standardPenalty: 'Section 36(1) Schedule Review',
    description: 'Specific commodities packed in standardized quantities (Second Schedule) or exemptions applicable to small packages containing 10g/10ml or less (Rule 26) shall be conditionally evaluated.',
    source: 'Rule 26 & Schedules',
    version: '2011.amended',
    effective_from: '2011-04-01',
  },
];

export function getRuleById(id: string): ComplianceRule | undefined {
  return complianceRules.find((rule) => rule.id === id || rule.id.replace('RULE-', '') === id);
}

export function getRulesByCategory(category: string): ComplianceRule[] {
  return complianceRules.filter((rule) => rule.clause.toLowerCase().includes(category.toLowerCase()));
}

export function getMandatoryRules(): ComplianceRule[] {
  return complianceRules.filter((rule) => rule.mandatory);
}